use crossterm::event::{KeyCode, KeyEvent};
use ratatui::{
    Frame,
    layout::{Alignment, Constraint, Direction, Layout, Rect},
    style::{Color, Modifier, Style},
    text::{Line, Span},
    widgets::{
        Block, Borders, Cell, List, ListItem, ListState, Paragraph, Row, Scrollbar,
        ScrollbarOrientation, ScrollbarState, Table, TableState, Wrap,
    },
};

use crate::core::event::UiCmd;

#[derive(Clone, Debug)]
pub struct Track {
    pub title: &'static str,
    pub artist: &'static str,
    pub album: &'static str,
    pub duration: &'static str,
}

#[derive(Clone, Debug)]
pub struct Album {
    pub title: &'static str,
    pub artist: &'static str,
    pub year: u16,
    pub track_count: u8,
}

#[derive(Clone, Debug)]
pub struct Artist {
    pub name: &'static str,
    pub genre: &'static str,
}

#[derive(Clone, Debug)]
pub struct Playlist {
    pub name: &'static str,
    pub track_count: usize,
}

fn placeholder_artists() -> Vec<Artist> {
    vec![
        Artist {
            name: "Kairiki Bear",
            genre: "Vocaloid",
        },
        Artist {
            name: "Yorushika",
            genre: "J-Rock",
        },
        Artist {
            name: "Yoasobi",
            genre: "J-Pop",
        },
        Artist {
            name: "25 Hours",
            genre: "T-Pop",
        },
        Artist {
            name: "２５時、ナイトコードで",
            genre: "Various",
        },
        Artist {
            name: "DECO *27",
            genre: "Vocaloid",
        },
    ]
}

// generated by AI =3
fn placeholder_tracks() -> Vec<Track> {
    vec![
        Track {
            title: "Midnight Drive",
            artist: "Neon Pulse",
            album: "Night Frequencies",
            duration: "3:42",
        },
        Track {
            title: "Solar Wind",
            artist: "Drift Engine",
            album: "Outer Signals",
            duration: "4:11",
        },
        Track {
            title: "Glass Architecture",
            artist: "Pale Static",
            album: "Structures",
            duration: "5:03",
        },
        Track {
            title: "Northern Lights",
            artist: "Frost Circuit",
            album: "Cold Logic",
            duration: "3:28",
        },
        Track {
            title: "Concrete Garden",
            artist: "Urban Haze",
            album: "Grey Sessions",
            duration: "4:55",
        },
        Track {
            title: "Deep Channel",
            artist: "Neon Pulse",
            album: "Night Frequencies",
            duration: "3:19",
        },
        Track {
            title: "Phase One",
            artist: "Signal Ghost",
            album: "Transmit",
            duration: "6:02",
        },
        Track {
            title: "Ember Coast",
            artist: "Drift Engine",
            album: "Outer Signals",
            duration: "3:44",
        },
        Track {
            title: "Static Memory",
            artist: "Pale Static",
            album: "Structures",
            duration: "4:30",
        },
        Track {
            title: "Low Horizon",
            artist: "Frost Circuit",
            album: "Cold Logic",
            duration: "3:55",
        },
        Track {
            title: "Citywide",
            artist: "Urban Haze",
            album: "Grey Sessions",
            duration: "5:17",
        },
        Track {
            title: "Signal Return",
            artist: "Signal Ghost",
            album: "Transmit",
            duration: "4:08",
        },
    ]
}

// generated by AI =3
fn placeholder_albums() -> Vec<Album> {
    vec![
        Album {
            title: "Night Frequencies",
            artist: "Neon Pulse",
            year: 2024,
            track_count: 10,
        },
        Album {
            title: "Outer Signals",
            artist: "Drift Engine",
            year: 2023,
            track_count: 9,
        },
        Album {
            title: "Structures",
            artist: "Pale Static",
            year: 2024,
            track_count: 12,
        },
        Album {
            title: "Cold Logic",
            artist: "Frost Circuit",
            year: 2022,
            track_count: 8,
        },
        Album {
            title: "Grey Sessions",
            artist: "Urban Haze",
            year: 2023,
            track_count: 11,
        },
        Album {
            title: "Transmit",
            artist: "Signal Ghost",
            year: 2024,
            track_count: 7,
        },
        Album {
            title: "Binary Dusk",
            artist: "Neon Pulse",
            year: 2022,
            track_count: 9,
        },
        Album {
            title: "Deep Scatter",
            artist: "Drift Engine",
            year: 2021,
            track_count: 10,
        },
    ]
}

fn placeholder_playlists() -> Vec<Playlist> {
    vec![
        Playlist {
            name: "Chill Vibes",
            track_count: 42,
        },
        Playlist {
            name: "Morning Motivation",
            track_count: 28,
        },
        Playlist {
            name: "Cloudy Day Mood",
            track_count: 35,
        },
        Playlist {
            name: "Focus",
            track_count: 19,
        },
        Playlist {
            name: "Gymday Sprechchor",
            track_count: 55,
        },
    ]
}

const PLACEHOLDER_LYRICS: &str = "\
    goop goop
    poop poop
    goop poop
    bloop moop
    shmoop
    doop doop
    gloop moop
    sloop doop
    boop boop
";

const LYRICS_LINE_COUNT: u16 = 9;

#[derive(Default, Debug, Clone, PartialEq)]
pub enum Focus {
    #[default]
    Main,
    LeftPanel,
    RightPanel,
    Playbar,
}

#[derive(Default, Debug, Clone, PartialEq)]
pub enum RightPanelKind {
    #[default]
    Queue,
    Lyrics,
    Related,
}

impl RightPanelKind {
    const ALL: &'static [RightPanelKind] = &[
        RightPanelKind::Queue,
        RightPanelKind::Lyrics,
        RightPanelKind::Related,
    ];

    fn label(&self) -> &'static str {
        match self {
            RightPanelKind::Queue => "Queue",
            RightPanelKind::Lyrics => "Lyrics",
            RightPanelKind::Related => "Related",
        }
    }

    fn next(&self) -> Self {
        let idx = Self::ALL.iter().position(|k| k == self).unwrap_or(0);
        Self::ALL[(idx + 1) % Self::ALL.len()].clone()
    }

    fn prev(&self) -> Self {
        let idx = Self::ALL.iter().position(|k| k == self).unwrap_or(0);
        Self::ALL[(idx + Self::ALL.len() - 1) % Self::ALL.len()].clone()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum SidebarTarget {
    LikedSongs,
    Albums,
    Artists,
    Playlists,
    Playlist(usize),
}

#[derive(Debug)]
enum SidebarRow {
    Header(&'static str),
    Nav {
        label: &'static str,
        target: SidebarTarget,
    },
    PlaylistRow {
        idx: usize,
        name: &'static str,
        count: usize,
    },
}

impl SidebarRow {
    fn is_selectable(&self) -> bool {
        !matches!(self, SidebarRow::Header(_))
    }
}

#[derive(Debug)]
pub struct LeftSideState {
    rows: Vec<SidebarRow>,
    list_state: ListState,
}

impl Default for LeftSideState {
    fn default() -> Self {
        let mut rows: Vec<SidebarRow> = vec![
            SidebarRow::Header("Browse"),
            SidebarRow::Nav {
                label: "Liked Songs",
                target: SidebarTarget::LikedSongs,
            },
            SidebarRow::Nav {
                label: "Albums",
                target: SidebarTarget::Albums,
            },
            SidebarRow::Nav {
                label: "Artists",
                target: SidebarTarget::Artists,
            },
            SidebarRow::Nav {
                label: "Playlists",
                target: SidebarTarget::Playlists,
            },
            SidebarRow::Header("Your Playlists"),
        ];
        for (idx, p) in placeholder_playlists().iter().enumerate() {
            rows.push(SidebarRow::PlaylistRow {
                idx,
                name: p.name,
                count: p.track_count,
            });
        }
        let first = rows.iter().position(|r| r.is_selectable()).unwrap_or(0);
        let mut list_state = ListState::default();
        list_state.select(Some(first));
        Self { rows, list_state }
    }
}

impl LeftSideState {
    fn selected_idx(&self) -> usize {
        self.list_state.selected().unwrap_or(0)
    }

    fn select_next(&mut self) {
        let cur = self.selected_idx();
        let next = (cur + 1..self.rows.len()).find(|&i| self.rows[i].is_selectable());
        if let Some(i) = next {
            self.list_state.select(Some(i));
        }
    }

    fn select_prev(&mut self) {
        let cur = self.selected_idx();
        let prev = (0..cur).rev().find(|&i| self.rows[i].is_selectable());
        if let Some(i) = prev {
            self.list_state.select(Some(i));
        }
    }

    fn selected_target(&self) -> Option<SidebarTarget> {
        match &self.rows[self.selected_idx()] {
            SidebarRow::Nav { target, .. } => Some(target.clone()),
            SidebarRow::PlaylistRow { idx, .. } => Some(SidebarTarget::Playlist(*idx)),
            SidebarRow::Header(_) => None,
        }
    }
}

#[derive(Debug)]
pub struct MainPanelState {
    pub content: MainContent,
    pub table_state: TableState,
}

impl Default for MainPanelState {
    fn default() -> Self {
        let mut table_state = TableState::default();
        table_state.select(Some(0));
        Self {
            content: MainContent::default(),
            table_state,
        }
    }
}

impl MainPanelState {
    fn select_next(&mut self) {
        let max = self.content.len().saturating_sub(1);
        let cur = self.table_state.selected().unwrap_or(0);
        self.table_state.select(Some((cur + 1).min(max)));
    }

    fn select_prev(&mut self) {
        let cur = self.table_state.selected().unwrap_or(0);
        self.table_state.select(Some(cur.saturating_sub(1)));
    }
}

#[derive(Debug)]
pub struct QueueState {
    pub now_playing: Track,
    pub upcoming: Vec<Track>,
    pub list_state: ListState,
}

impl Default for QueueState {
    fn default() -> Self {
        let mut all = placeholder_tracks();
        let now_playing = all.remove(0);
        let mut list_state = ListState::default();
        list_state.select(Some(0));
        Self {
            now_playing,
            upcoming: all,
            list_state,
        }
    }
}

#[derive(Debug)]
pub struct RightPanelState {
    pub kind: RightPanelKind,
    pub tab_offset: usize,
    pub queue: QueueState,
    pub lyrics_scroll: u16,
    pub lyrics_visible_height: u16,
    pub lyrics_timed: bool,
    pub related: Vec<Track>,
    pub related_state: ListState,
}

impl Default for RightPanelState {
    fn default() -> Self {
        Self {
            kind: RightPanelKind::default(),
            tab_offset: 0,
            queue: QueueState::default(),
            lyrics_scroll: 0,
            lyrics_visible_height: 0,
            lyrics_timed: false,
            related: placeholder_tracks(),
            related_state: ListState::default(),
        }
    }
}

#[derive(Debug)]
pub enum MainContent {
    Albums(Vec<Album>),
    Artists(Vec<Artist>),
    Playlists(Vec<Playlist>),
    Tracks {
        title: &'static str,
        items: Vec<Track>,
    },
}

impl Default for MainContent {
    fn default() -> Self {
        MainContent::Albums(placeholder_albums())
    }
}

impl MainContent {
    fn panel_title(&self) -> &str {
        match self {
            MainContent::Albums(_) => "Albums",
            MainContent::Artists(_) => "Artists",
            MainContent::Playlists(_) => "Playlists",
            MainContent::Tracks { title, .. } => title,
        }
    }

    fn len(&self) -> usize {
        match self {
            MainContent::Albums(v) => v.len(),
            MainContent::Artists(v) => v.len(),
            MainContent::Playlists(v) => v.len(),
            MainContent::Tracks { items, .. } => items.len(),
        }
    }
}

#[derive(Debug)]
pub struct PlaybarState {
    pub playing: bool,
    pub progress: f64,
    pub volume: u8,
    pub track: Track,
    pub elapsed: &'static str,
    pub total: &'static str,
}

impl Default for PlaybarState {
    fn default() -> Self {
        Self {
            playing: false,
            progress: 0.35,
            volume: 70,
            track: placeholder_tracks().remove(0),
            elapsed: "1:23",
            total: "3:42",
        }
    }
}

#[derive(Default, Debug)]
pub struct MainView {
    pub focus: Focus,
    pub left: LeftSideState,
    pub main: MainPanelState,
    pub right: RightPanelState,
    pub playbar: PlaybarState,
}

impl MainView {
    fn handle_left(&mut self, key: KeyEvent) -> Option<UiCmd> {
        match key.code {
            KeyCode::Char('j') => self.left.select_next(),
            KeyCode::Char('k') => self.left.select_prev(),
            KeyCode::Char('l') => {
                if let Some(target) = self.left.selected_target() {
                    self.focus = Focus::Main;
                    self.navigate_main(target);
                }
            }
            _ => {}
        }
        None
    }

    fn navigate_main(&mut self, target: SidebarTarget) {
        self.main.content = match target {
            SidebarTarget::LikedSongs => MainContent::Tracks {
                title: "Liked Songs",
                items: placeholder_tracks(),
            },
            SidebarTarget::Albums => MainContent::Albums(placeholder_albums()),
            SidebarTarget::Artists => MainContent::Artists(placeholder_artists()),
            SidebarTarget::Playlists => MainContent::Playlists(placeholder_playlists()),
            SidebarTarget::Playlist(idx) => MainContent::Tracks {
                title: placeholder_playlists()[idx].name,
                items: placeholder_tracks(),
            },
        };
        let mut ts = TableState::default();
        ts.select(Some(0));
        self.main.table_state = ts;
    }

    fn handle_main(&mut self, key: KeyEvent) -> Option<UiCmd> {
        match key.code {
            KeyCode::Char('j') => self.main.select_next(),
            KeyCode::Char('k') => self.main.select_prev(),
            KeyCode::Enter => { /* hook up UiCmd::Play later */ }
            _ => {}
        }
        None
    }

    fn handle_right(&mut self, key: KeyEvent) -> Option<UiCmd> {
        match key.code {
            KeyCode::Char('[') => {
                self.right.kind = self.right.kind.prev();
            }
            KeyCode::Char(']') => {
                self.right.kind = self.right.kind.next();
            }
            KeyCode::Char('j') => match self.right.kind {
                RightPanelKind::Queue => {
                    let max = self.right.queue.upcoming.len().saturating_sub(1);
                    let cur = self.right.queue.list_state.selected().unwrap_or(0);
                    self.right.queue.list_state.select(Some((cur + 1).min(max)));
                }
                RightPanelKind::Lyrics => {
                    if self.right.lyrics_timed {
                        let max =
                            LYRICS_LINE_COUNT.saturating_sub(self.right.lyrics_visible_height);
                        self.right.lyrics_scroll = (self.right.lyrics_scroll + 1).min(max);
                    }
                }
                RightPanelKind::Related => {
                    let max = self.right.related.len().saturating_sub(1);
                    let cur = self.right.related_state.selected().unwrap_or(0);
                    self.right.related_state.select(Some((cur + 1).min(max)));
                }
            },
            KeyCode::Char('k') => match self.right.kind {
                RightPanelKind::Queue => {
                    let cur = self.right.queue.list_state.selected().unwrap_or(0);
                    self.right
                        .queue
                        .list_state
                        .select(Some(cur.saturating_sub(1)));
                }
                RightPanelKind::Lyrics => {
                    if self.right.lyrics_timed {
                        self.right.lyrics_scroll = self.right.lyrics_scroll.saturating_sub(1);
                    }
                }
                RightPanelKind::Related => {
                    let cur = self.right.related_state.selected().unwrap_or(0);
                    self.right.related_state.select(Some(cur.saturating_sub(1)));
                }
            },
            _ => {}
        }
        None
    }

    fn handle_playbar(&mut self, key: KeyEvent) -> Option<UiCmd> {
        match key.code {
            KeyCode::Char('-') => {
                self.playbar.volume = self.playbar.volume.saturating_sub(5);
            }
            KeyCode::Char('+') | KeyCode::Char('=') => {
                self.playbar.volume = (self.playbar.volume + 5).min(100);
            }
            KeyCode::Char('l') => return Some(UiCmd::Logout),
            _ => {}
        }
        None
    }

    pub fn handle_key(&mut self, key: KeyEvent) -> Option<UiCmd> {
        match key.code {
            KeyCode::Tab => {
                self.focus = match self.focus {
                    Focus::LeftPanel => Focus::Main,
                    Focus::Main => Focus::RightPanel,
                    Focus::RightPanel => Focus::Playbar,
                    Focus::Playbar => Focus::LeftPanel,
                };
                return None;
            }
            KeyCode::BackTab => {
                self.focus = match self.focus {
                    Focus::LeftPanel => Focus::Playbar,
                    Focus::Main => Focus::LeftPanel,
                    Focus::RightPanel => Focus::Main,
                    Focus::Playbar => Focus::RightPanel,
                };
                return None;
            }
            KeyCode::Char(' ') => {
                self.playbar.playing = !self.playbar.playing;
                return None;
            }
            _ => {}
        }

        match self.focus {
            Focus::LeftPanel => self.handle_left(key),
            Focus::Main => self.handle_main(key),
            Focus::RightPanel => self.handle_right(key),
            Focus::Playbar => self.handle_playbar(key),
        }
    }
}

impl MainView {
    pub fn render(&mut self, frame: &mut Frame) {
        let root = Layout::default()
            .direction(Direction::Vertical)
            .constraints([Constraint::Fill(1), Constraint::Length(4)])
            .split(frame.area());

        let body = Layout::default()
            .direction(Direction::Horizontal)
            .constraints([
                Constraint::Percentage(20),
                Constraint::Fill(1),
                Constraint::Percentage(30),
            ])
            .split(root[0]);

        self.render_left(frame, body[0]);
        self.render_main(frame, body[1]);
        self.render_right(frame, body[2]);
        self.render_playbar(frame, root[1]);
    }

    fn render_left(&mut self, frame: &mut Frame, area: Rect) {
        let focused = self.focus == Focus::LeftPanel;

        let items: Vec<ListItem> =
            self.left
                .rows
                .iter()
                .map(|row| match row {
                    SidebarRow::Header(label) => ListItem::new(Line::from(Span::styled(
                        format!(" {} ", label),
                        Style::default()
                            .fg(Color::DarkGray)
                            .add_modifier(Modifier::BOLD),
                    ))),
                    SidebarRow::Nav { label, .. } => {
                        ListItem::new(Line::from(Span::raw(format!("  {}", label))))
                    }
                    SidebarRow::PlaylistRow { name, .. } => ListItem::new(Line::from(
                        Span::styled(format!("  {}", name), Style::default().fg(Color::DarkGray)),
                    )),
                })
                .collect();

        let list = List::new(items)
            .block(block_for("Library", focused))
            .highlight_style(
                Style::default()
                    .fg(Color::Green)
                    .add_modifier(Modifier::BOLD),
            )
            .highlight_symbol("►");

        frame.render_stateful_widget(list, area, &mut self.left.list_state);
    }

    fn render_main(&mut self, frame: &mut Frame, area: Rect) {
        let focused = self.focus == Focus::Main;
        let title = self.main.content.panel_title().to_string();
        let inner = inset(area);

        let padded = Rect {
            height: area.height.saturating_sub(1),
            ..area
        };

        let sel = self.main.table_state.selected().unwrap_or(0);
        let total = self.main.content.len();

        let visible_rows = inner.height.saturating_sub(2) as usize;

        let hl = Style::default()
            .fg(Color::Green)
            .add_modifier(Modifier::BOLD);
        let hdr = Style::default()
            .fg(Color::DarkGray)
            .add_modifier(Modifier::BOLD);

        match &self.main.content {
            MainContent::Albums(albums) => {
                let rows: Vec<Row> = albums
                    .iter()
                    .map(|a| {
                        Row::new(vec![
                            Cell::from(a.title),
                            Cell::from(a.artist),
                            Cell::from(a.year.to_string()),
                            Cell::from(format!("{} tracks", a.track_count)),
                        ])
                    })
                    .collect();
                let table = Table::new(
                    rows,
                    [
                        Constraint::Fill(2),
                        Constraint::Fill(2),
                        Constraint::Length(6),
                        Constraint::Length(9),
                    ],
                )
                .header(
                    Row::new(["Title", "Artist", "Year", "Tracks"])
                        .style(hdr)
                        .bottom_margin(1),
                )
                .block(block_for(&title, focused))
                .row_highlight_style(hl)
                .highlight_symbol("► ");
                frame.render_stateful_widget(table, padded, &mut self.main.table_state);
            }
            MainContent::Artists(artists) => {
                let rows: Vec<Row> = artists
                    .iter()
                    .map(|a| Row::new(vec![Cell::from(a.name), Cell::from(a.genre)]))
                    .collect();
                let table = Table::new(rows, [Constraint::Fill(2), Constraint::Fill(1)])
                    .header(Row::new(["Artist", "Genre"]).style(hdr).bottom_margin(1))
                    .block(block_for(&title, focused))
                    .row_highlight_style(hl)
                    .highlight_symbol("► ");
                frame.render_stateful_widget(table, padded, &mut self.main.table_state);
            }
            MainContent::Playlists(playlists) => {
                let rows: Vec<Row> = playlists
                    .iter()
                    .map(|p| {
                        Row::new(vec![
                            Cell::from(p.name),
                            Cell::from(p.track_count.to_string()),
                        ])
                    })
                    .collect();
                let table = Table::new(rows, [Constraint::Fill(1), Constraint::Length(8)])
                    .header(Row::new(["Name", "Tracks"]).style(hdr).bottom_margin(1))
                    .block(block_for(&title, focused))
                    .row_highlight_style(hl)
                    .highlight_symbol("► ");
                frame.render_stateful_widget(table, padded, &mut self.main.table_state);
            }
            MainContent::Tracks { items, .. } => {
                let rows: Vec<Row> = items
                    .iter()
                    .enumerate()
                    .map(|(i, t)| {
                        Row::new(vec![
                            Cell::from(format!("{:>2}", i + 1)),
                            Cell::from(t.title),
                            Cell::from(t.artist),
                            Cell::from(t.album),
                            Cell::from(t.duration),
                        ])
                    })
                    .collect();
                let table = Table::new(
                    rows,
                    [
                        Constraint::Length(3),
                        Constraint::Fill(2),
                        Constraint::Fill(2),
                        Constraint::Fill(2),
                        Constraint::Length(5),
                    ],
                )
                .header(
                    Row::new(["#", "Title", "Artist", "Album", ""])
                        .style(hdr)
                        .bottom_margin(1),
                )
                .block(block_for(&title, focused))
                .row_highlight_style(hl)
                .highlight_symbol("► ");
                frame.render_stateful_widget(table, padded, &mut self.main.table_state);
            }
        }

        if total > visible_rows {
            let mut sb = ScrollbarState::new(total).position(sel);
            frame.render_stateful_widget(
                Scrollbar::new(ScrollbarOrientation::VerticalRight)
                    .style(Style::default().fg(Color::DarkGray)),
                inner,
                &mut sb,
            );
        }
    }

    fn render_right(&mut self, frame: &mut Frame, area: Rect) {
        let focused = self.focus == Focus::RightPanel;
        let all = RightPanelKind::ALL;
        let active_idx = all.iter().position(|k| k == &self.right.kind).unwrap_or(0);

        let available = area.width.saturating_sub(4) as usize;
        let left_ellipsis = if self.right.tab_offset > 0 { 4 } else { 0 };
        let mut used = left_ellipsis;
        let mut vis = 0usize;

        for kind in &all[self.right.tab_offset..] {
            let cost = kind.label().len() + 3;
            let right = if self.right.tab_offset + vis + 1 < all.len() {
                4
            } else {
                0
            };
            if used + cost + right > available {
                break;
            }
            used += cost;
            vis += 1;
        }
        let vis = vis.max(1);

        if active_idx < self.right.tab_offset {
            self.right.tab_offset = active_idx;
        } else if active_idx >= self.right.tab_offset + vis {
            self.right.tab_offset = active_idx.saturating_sub(vis - 1);
        }

        let vis_end = (self.right.tab_offset + vis).min(all.len());

        let mut title_spans: Vec<Span> = vec![Span::raw(" ")];

        if self.right.tab_offset > 0 {
            title_spans.push(Span::styled("... │ ", Style::default().fg(Color::DarkGray)));
        }

        let visible_slice = &all[self.right.tab_offset..vis_end];
        for (i, kind) in visible_slice.iter().enumerate() {
            let is_active = kind == &self.right.kind;
            title_spans.push(if is_active {
                Span::styled(
                    kind.label(),
                    Style::default()
                        .fg(Color::Green)
                        .add_modifier(Modifier::BOLD),
                )
            } else {
                Span::styled(kind.label(), Style::default().fg(Color::DarkGray))
            });
            let is_last_visible = i == visible_slice.len() - 1;
            if !is_last_visible {
                title_spans.push(Span::styled(" │ ", Style::default().fg(Color::DarkGray)));
            } else {
                title_spans.push(Span::raw(" "));
            }
        }

        if vis_end < all.len() {
            title_spans.push(Span::styled(" ...", Style::default().fg(Color::DarkGray)));
        }

        let block = Block::default()
            .borders(Borders::ALL)
            .border_style(border_style(focused))
            .title(Line::from(title_spans))
            .title_bottom(Line::from(Span::styled(
                " [/] tab ",
                Style::default().fg(Color::DarkGray),
            )));

        frame.render_widget(block, area);
        let inner = inset(area);

        let kind = self.right.kind.clone();
        match kind {
            RightPanelKind::Queue => self.render_queue(frame, inner),
            RightPanelKind::Lyrics => self.render_lyrics(frame, inner),
            RightPanelKind::Related => self.render_related(frame, inner),
        }
    }

    fn render_queue(&mut self, frame: &mut Frame, area: Rect) {
        let sections = Layout::default()
            .direction(Direction::Vertical)
            .constraints([
                Constraint::Length(5), // now playing
                Constraint::Length(1), // separator
                Constraint::Fill(1),   // upcoming
            ])
            .split(area);

        {
            let np = &self.right.queue.now_playing;
            frame.render_widget(
                Paragraph::new(vec![
                    Line::from(Span::styled(
                        "Now Playing",
                        Style::default().fg(Color::DarkGray),
                    )),
                    Line::from(""),
                    Line::from(Span::styled(
                        np.title,
                        Style::default()
                            .fg(Color::White)
                            .add_modifier(Modifier::BOLD),
                    )),
                    Line::from(Span::styled(
                        format!("{}  ·  {}", np.artist, np.album),
                        Style::default().fg(Color::DarkGray),
                    )),
                    Line::from(Span::styled(np.duration, Style::default().fg(Color::Green))),
                ]),
                sections[0],
            );
        }

        frame.render_widget(
            Paragraph::new(Span::styled(
                "─".repeat(area.width.saturating_sub(2) as usize),
                Style::default().fg(Color::DarkGray),
            )),
            sections[1],
        );

        let title_w = sections[2].width.saturating_sub(8) as usize;
        let items: Vec<ListItem> = self
            .right
            .queue
            .upcoming
            .iter()
            .map(|t| {
                ListItem::new(Line::from(vec![
                    Span::styled(
                        format!("{:<width$}", t.title, width = title_w.min(28)),
                        Style::default().fg(Color::DarkGray),
                    ),
                    Span::styled(t.duration, Style::default().fg(Color::DarkGray)),
                ]))
            })
            .collect();

        let list = List::new(items)
            .highlight_style(
                Style::default()
                    .fg(Color::White)
                    .add_modifier(Modifier::BOLD),
            )
            .highlight_symbol("► ");

        frame.render_stateful_widget(list, sections[2], &mut self.right.queue.list_state);
    }

    fn render_lyrics(&mut self, frame: &mut Frame, area: Rect) {
        self.right.lyrics_visible_height = area.height;
        frame.render_widget(
            Paragraph::new(PLACEHOLDER_LYRICS)
                .wrap(Wrap { trim: false })
                .scroll((self.right.lyrics_scroll, 0))
                .style(Style::default().fg(Color::DarkGray)),
            area,
        );
    }

    fn render_related(&mut self, frame: &mut Frame, area: Rect) {
        let sections = Layout::default()
            .direction(Direction::Vertical)
            .constraints([Constraint::Length(2), Constraint::Fill(1)])
            .split(area);

        // scoped so borrow of now_playing is released before list render
        {
            let similar_to = self.right.queue.now_playing.title;
            frame.render_widget(
                Paragraph::new(vec![
                    Line::from(Span::styled(
                        format!("Similar to: {}", similar_to),
                        Style::default().fg(Color::DarkGray),
                    )),
                    Line::from(Span::styled(
                        "─".repeat(area.width.saturating_sub(2) as usize),
                        Style::default().fg(Color::DarkGray),
                    )),
                ]),
                sections[0],
            );
        }

        let items: Vec<ListItem> = self
            .right
            .related
            .iter()
            .map(|t| {
                ListItem::new(vec![
                    Line::from(Span::styled(t.title, Style::default().fg(Color::White))),
                    Line::from(Span::styled(
                        format!("  {}", t.artist),
                        Style::default().fg(Color::DarkGray),
                    )),
                ])
            })
            .collect();

        let list = List::new(items)
            .highlight_style(
                Style::default()
                    .fg(Color::Green)
                    .add_modifier(Modifier::BOLD),
            )
            .highlight_symbol("► ");

        frame.render_stateful_widget(list, sections[1], &mut self.right.related_state);
    }

    fn render_playbar(&self, frame: &mut Frame, area: Rect) {
        let focused = self.focus == Focus::Playbar;
        frame.render_widget(block_for("", focused), area);
        let inner = inset(area);

        let cols = Layout::default()
            .direction(Direction::Horizontal)
            .constraints([
                Constraint::Percentage(25),
                Constraint::Fill(1),
                Constraint::Percentage(25),
            ])
            .split(inner);

        let t = &self.playbar.track;
        frame.render_widget(
            Paragraph::new(vec![
                Line::from(Span::styled(
                    t.title,
                    Style::default()
                        .fg(Color::White)
                        .add_modifier(Modifier::BOLD),
                )),
                Line::from(Span::styled(
                    format!("{}  ·  {}", t.artist, t.album),
                    Style::default().fg(Color::DarkGray),
                )),
            ]),
            cols[0],
        );

        let play = if self.playbar.playing { "⏸" } else { "▶" };
        let bar_w = cols[1].width.saturating_sub(17) as usize;
        let filled = ((bar_w as f64) * self.playbar.progress) as usize;
        frame.render_widget(
            Paragraph::new(vec![
                Line::from(Span::styled(
                    format!("⏮  {}  ⏭", play),
                    Style::default().fg(Color::White),
                )),
                Line::from(Span::styled(
                    format!(
                        "{} {}{} {}",
                        self.playbar.elapsed,
                        "█".repeat(filled),
                        "─".repeat(bar_w.saturating_sub(filled)),
                        self.playbar.total
                    ),
                    Style::default().fg(Color::Green),
                )),
            ])
            .alignment(Alignment::Center),
            cols[1],
        );

        let vol_w = 10usize;
        let vol_f = ((vol_w as f64) * self.playbar.volume as f64 / 100.0) as usize;
        frame.render_widget(
            Paragraph::new(vec![Line::from(vec![
                Span::styled("vol  ", Style::default().fg(Color::DarkGray)),
                Span::styled(
                    format!(
                        "{}{}",
                        "█".repeat(vol_f),
                        "─".repeat(vol_w - vol_f.min(vol_w))
                    ),
                    Style::default().fg(Color::Green),
                ),
            ])])
            .alignment(Alignment::Right),
            cols[2],
        );
    }
}

fn block_for(title: &str, focused: bool) -> Block<'_> {
    Block::default()
        .borders(Borders::ALL)
        .border_style(border_style(focused))
        .title(Span::styled(
            format!(" {} ", title),
            Style::default().fg(if focused {
                Color::Green
            } else {
                Color::DarkGray
            }),
        ))
}

fn border_style(focused: bool) -> Style {
    if focused {
        Style::default().fg(Color::Green)
    } else {
        Style::default().fg(Color::DarkGray)
    }
}

fn inset(area: Rect) -> Rect {
    Rect {
        x: area.x.saturating_add(1),
        y: area.y.saturating_add(1),
        width: area.width.saturating_sub(2),
        height: area.height.saturating_sub(2),
    }
}
